export type JobDTO = {
  id: string;
  title: string;
  description: string;
  location: string;
  rawLocation?: string;
  city: string;
  country: string;
  employmentType: string;
  experienceLevel: string;
  department: string;
  team: string;
  skills: string[];
  salary: string | null;
  remoteType: string;
  applicationUrl: string;
  sourceUrl: string;
  sourceType: string;
  postedAt: string | null;
  discoveredAt: string;
  lastSeenAt: string;
  isNew: boolean;
  isActive: boolean;
  isRelevant: boolean;
  relevanceScore: number;
  matchReasons: string[];
  userStatus: string;
  aiFitScore?: number | null;
  aiRecommendation?: string | null;
  aiSummary?: string | null;
  aiStrengths?: string[];
  aiGaps?: string[];
  aiConcerns?: string[];
  aiReasoning?: string | null;
  aiExperienceFit?: string | null;
  aiSkillFit?: string | null;
  aiRoleFit?: string | null;
  aiLocationFit?: string | null;
  aiRequiredSkillsMatched?: string[];
  aiRequiredSkillsMissing?: string[];
  aiPreferredSkillsMatched?: string[];
  aiPreferredSkillsMissing?: string[];
  aiSeniority?: string | null;
  aiIsEarlyCareer?: boolean | null;
  aiRequiresSignificantExperience?: boolean | null;
  aiStatus?: string;
  aiAnalyzedAt?: string | null;
  priorityScore?: number;
  freshnessScore?: number;
  scoreDifference?: number | null;
  disagreement?: "REVIEW_RULE_ENGINE" | "POSSIBLE_FALSE_NEGATIVE" | null;
  company: {
    id: string;
    name: string;
    slug: string;
    logo: string | null;
    tier: string;
    careersUrl: string;
  };
};

export type CompanyDTO = {
  id: string;
  name: string;
  slug: string;
  logo: string | null;
  careersUrl: string;
  sourceType: string;
  tier: string;
  enabled: boolean;
  lastCheckedAt: string | null;
  checkStatus: string;
  lastError: string | null;
  lastBlockReason?: string | null;
  lastSuccessAt?: string | null;
  failureCount?: number;
  blockedCount?: number;
  rateLimitCount?: number;
  jobsFetched?: number;
  jobsParsed?: number;
  jobsRejected?: number;
  averageLatencyMs?: number;
  jobsFound: number;
  relevant: number;
  isNew: number;
  sourceStatus?: string;
  category?: string;
  priority?: string;
  indiaHiring?: string;
  sourceVerifiedAt?: string | null;
  consecutiveFailures?: number;
  sourceNotes?: string;
};

export type CompanyCoverage = {
  tracked: number;
  verified: number;
  unverified: number;
  unsupported: number;
  failed: number;
  disabled: number;
  ats: Record<string, number>;
};
