import type { SourceType } from "@/lib/adapters/types";
import type { CompanySeed } from "./companies";

/** New product companies. All start UNVERIFIED and disabled until official sources succeed. */
export const ADDITIONAL_COMPANY_SEEDS: CompanySeed[] = [
  // Big tech / global product
  {
    name: "Netflix",
    slug: "netflix",
    careersUrl: "https://jobs.netflix.com/",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "netflix.com",
    category: "BIG_TECH",
    priority: "A",
    indiaHiring: "unknown",
  },
  {
    name: "Walmart Global Tech",
    slug: "walmart-global-tech",
    careersUrl: "https://careers.walmart.com/",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "walmart.com",
    category: "BIG_TECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Cisco",
    slug: "cisco",
    careersUrl: "https://jobs.cisco.com/",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "cisco.com",
    category: "BIG_TECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Intel",
    slug: "intel",
    careersUrl: "https://jobs.intel.com/",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "intel.com",
    category: "BIG_TECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Qualcomm",
    slug: "qualcomm",
    careersUrl: "https://careers.qualcomm.com/",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "qualcomm.com",
    category: "BIG_TECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "AMD",
    slug: "amd",
    careersUrl: "https://careers.amd.com/",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "amd.com",
    category: "BIG_TECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "PayPal",
    slug: "paypal",
    careersUrl: "https://careers.pypl.com/",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "paypal.com",
    category: "FINTECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Visa",
    slug: "visa",
    careersUrl: "https://usa.visa.com/careers.html",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "visa.com",
    category: "FINTECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Mastercard",
    slug: "mastercard",
    careersUrl: "https://careers.mastercard.com/",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "mastercard.com",
    category: "FINTECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "JPMorgan Chase",
    slug: "jpmorgan-chase",
    careersUrl: "https://careers.jpmorgan.com/",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "jpmorgan.com",
    category: "FINTECH",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Goldman Sachs",
    slug: "goldman-sachs",
    careersUrl: "https://www.goldmansachs.com/careers/",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "goldmansachs.com",
    category: "FINTECH",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Morgan Stanley",
    slug: "morgan-stanley",
    careersUrl: "https://www.morganstanley.com/careers",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "morganstanley.com",
    category: "FINTECH",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Bloomberg",
    slug: "bloomberg",
    careersUrl: "https://www.bloomberg.com/company/careers/",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "bloomberg.com",
    category: "FINTECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Siemens",
    slug: "siemens",
    careersUrl: "https://www.siemens.com/global/en/company/jobs.html",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "siemens.com",
    category: "OTHER_PRODUCT",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Bosch",
    slug: "bosch",
    careersUrl: "https://www.bosch.in/careers/",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "bosch.com",
    category: "OTHER_PRODUCT",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Samsung",
    slug: "samsung",
    careersUrl: "https://www.samsung.com/in/about-us/careers/",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "samsung.com",
    category: "CONSUMER_TECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Sony",
    slug: "sony",
    careersUrl: "https://www.sony.com/en/careers/",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "sony.com",
    category: "CONSUMER_TECH",
    priority: "C",
    indiaHiring: "unknown",
  },

  // SaaS / developer tools with known official ATS boards
  {
    name: "MongoDB",
    slug: "mongodb",
    careersUrl: "https://www.mongodb.com/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "mongodb" },
    tier: "saas",
    enabled: false,
    domain: "mongodb.com",
    category: "DEVTOOLS",
    priority: "A",
    indiaHiring: "unknown",
  },
  {
    name: "Confluent",
    slug: "confluent",
    careersUrl: "https://www.confluent.io/careers/",
    sourceType: "ashby",
    sourceConfig: { boardToken: "confluent" },
    tier: "saas",
    enabled: false,
    domain: "confluent.io",
    category: "CLOUD",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "HashiCorp",
    slug: "hashicorp",
    careersUrl: "https://www.hashicorp.com/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "hashicorp" },
    tier: "saas",
    enabled: false,
    domain: "hashicorp.com",
    category: "DEVTOOLS",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Grafana Labs",
    slug: "grafana",
    careersUrl: "https://grafana.com/about/careers/",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "grafanalabs" },
    tier: "saas",
    enabled: false,
    domain: "grafana.com",
    category: "DEVTOOLS",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Sentry",
    slug: "sentry",
    careersUrl: "https://sentry.io/careers/",
    sourceType: "ashby",
    sourceConfig: { boardToken: "sentry" },
    tier: "saas",
    enabled: false,
    domain: "sentry.io",
    category: "DEVTOOLS",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Vercel",
    slug: "vercel",
    careersUrl: "https://vercel.com/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "vercel" },
    tier: "saas",
    enabled: false,
    domain: "vercel.com",
    category: "DEVTOOLS",
    priority: "A",
    indiaHiring: "unknown",
  },
  {
    name: "Asana",
    slug: "asana",
    careersUrl: "https://asana.com/jobs",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "asana" },
    tier: "saas",
    enabled: false,
    domain: "asana.com",
    category: "SAAS",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Intercom",
    slug: "intercom",
    careersUrl: "https://www.intercom.com/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "intercom" },
    tier: "saas",
    enabled: false,
    domain: "intercom.com",
    category: "SAAS",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Gusto",
    slug: "gusto",
    careersUrl: "https://gusto.com/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "gusto" },
    tier: "saas",
    enabled: false,
    domain: "gusto.com",
    category: "SAAS",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Duolingo",
    slug: "duolingo",
    careersUrl: "https://careers.duolingo.com/",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "duolingo" },
    tier: "saas",
    enabled: false,
    domain: "duolingo.com",
    category: "CONSUMER_TECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "DoorDash",
    slug: "doordash",
    careersUrl: "https://careers.doordash.com/",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "doordash" },
    tier: "saas",
    enabled: false,
    domain: "doordash.com",
    category: "CONSUMER_TECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Lyft",
    slug: "lyft",
    careersUrl: "https://www.lyft.com/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "lyft" },
    tier: "saas",
    enabled: false,
    domain: "lyft.com",
    category: "CONSUMER_TECH",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Instacart",
    slug: "instacart",
    careersUrl: "https://instacart.careers/",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "instacart" },
    tier: "saas",
    enabled: false,
    domain: "instacart.com",
    category: "CONSUMER_TECH",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Plaid",
    slug: "plaid",
    careersUrl: "https://plaid.com/careers/",
    sourceType: "ashby",
    sourceConfig: { boardToken: "plaid" },
    tier: "saas",
    enabled: false,
    domain: "plaid.com",
    category: "FINTECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Brex",
    slug: "brex",
    careersUrl: "https://www.brex.com/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "brex" },
    tier: "saas",
    enabled: false,
    domain: "brex.com",
    category: "FINTECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Affirm",
    slug: "affirm",
    careersUrl: "https://www.affirm.com/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "affirm" },
    tier: "saas",
    enabled: false,
    domain: "affirm.com",
    category: "FINTECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Ramp",
    slug: "ramp",
    careersUrl: "https://ramp.com/careers",
    sourceType: "ashby",
    sourceConfig: { boardToken: "ramp" },
    tier: "saas",
    enabled: false,
    domain: "ramp.com",
    category: "FINTECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Rippling",
    slug: "rippling",
    careersUrl: "https://www.rippling.com/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "rippling" },
    tier: "saas",
    enabled: false,
    domain: "rippling.com",
    category: "SAAS",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "LaunchDarkly",
    slug: "launchdarkly",
    careersUrl: "https://launchdarkly.com/careers/",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "launchdarkly" },
    tier: "saas",
    enabled: false,
    domain: "launchdarkly.com",
    category: "DEVTOOLS",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "PagerDuty",
    slug: "pagerduty",
    careersUrl: "https://www.pagerduty.com/careers/",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "pagerduty" },
    tier: "saas",
    enabled: false,
    domain: "pagerduty.com",
    category: "DEVTOOLS",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Amplitude",
    slug: "amplitude",
    careersUrl: "https://amplitude.com/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "amplitude" },
    tier: "saas",
    enabled: false,
    domain: "amplitude.com",
    category: "SAAS",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Mixpanel",
    slug: "mixpanel",
    careersUrl: "https://mixpanel.com/jobs/",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "mixpanel" },
    tier: "saas",
    enabled: false,
    domain: "mixpanel.com",
    category: "SAAS",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Contentful",
    slug: "contentful",
    careersUrl: "https://www.contentful.com/careers/",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "contentful" },
    tier: "saas",
    enabled: false,
    domain: "contentful.com",
    category: "SAAS",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Algolia",
    slug: "algolia",
    careersUrl: "https://www.algolia.com/careers/",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "algolia" },
    tier: "saas",
    enabled: false,
    domain: "algolia.com",
    category: "DEVTOOLS",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "DigitalOcean",
    slug: "digitalocean",
    careersUrl: "https://www.digitalocean.com/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "digitalocean" },
    tier: "saas",
    enabled: false,
    domain: "digitalocean.com",
    category: "CLOUD",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Cloudinary",
    slug: "cloudinary",
    careersUrl: "https://cloudinary.com/careers",
    sourceType: "lever",
    sourceConfig: { boardToken: "cloudinary" },
    tier: "saas",
    enabled: false,
    domain: "cloudinary.com",
    category: "CLOUD",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Fivetran",
    slug: "fivetran",
    careersUrl: "https://www.fivetran.com/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "fivetran" },
    tier: "ai",
    enabled: false,
    domain: "fivetran.com",
    category: "CLOUD",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "dbt Labs",
    slug: "dbt-labs",
    careersUrl: "https://www.getdbt.com/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "dbtlabsinc" },
    tier: "ai",
    enabled: false,
    domain: "getdbt.com",
    category: "DEVTOOLS",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Cockroach Labs",
    slug: "cockroach-labs",
    careersUrl: "https://www.cockroachlabs.com/careers/",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "cockroachlabs" },
    tier: "saas",
    enabled: false,
    domain: "cockroachlabs.com",
    category: "DEVTOOLS",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Redis",
    slug: "redis",
    careersUrl: "https://redis.io/careers/",
    sourceType: "ashby",
    sourceConfig: { boardToken: "redis" },
    tier: "saas",
    enabled: false,
    domain: "redis.io",
    category: "DEVTOOLS",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "ClickHouse",
    slug: "clickhouse",
    careersUrl: "https://clickhouse.com/careers",
    sourceType: "ashby",
    sourceConfig: { boardToken: "clickhouse" },
    tier: "ai",
    enabled: false,
    domain: "clickhouse.com",
    category: "CLOUD",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Temporal",
    slug: "temporal",
    careersUrl: "https://temporal.io/careers",
    sourceType: "ashby",
    sourceConfig: { boardToken: "temporal" },
    tier: "saas",
    enabled: false,
    domain: "temporal.io",
    category: "DEVTOOLS",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Airbnb",
    slug: "airbnb",
    careersUrl: "https://careers.airbnb.com/",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "airbnb" },
    tier: "tier-1",
    enabled: false,
    domain: "airbnb.com",
    category: "CONSUMER_TECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Discord",
    slug: "discord",
    careersUrl: "https://discord.com/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "discord" },
    tier: "saas",
    enabled: false,
    domain: "discord.com",
    category: "CONSUMER_TECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Reddit",
    slug: "reddit",
    careersUrl: "https://www.redditinc.com/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "reddit" },
    tier: "saas",
    enabled: false,
    domain: "reddit.com",
    category: "CONSUMER_TECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Pinterest",
    slug: "pinterest",
    careersUrl: "https://www.pinterestcareers.com/",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "pinterest" },
    tier: "saas",
    enabled: false,
    domain: "pinterest.com",
    category: "CONSUMER_TECH",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Coinbase",
    slug: "coinbase",
    careersUrl: "https://www.coinbase.com/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "coinbase" },
    tier: "saas",
    enabled: false,
    domain: "coinbase.com",
    category: "FINTECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Robinhood",
    slug: "robinhood",
    careersUrl: "https://careers.robinhood.com/",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "robinhood" },
    tier: "saas",
    enabled: false,
    domain: "robinhood.com",
    category: "FINTECH",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Block",
    slug: "block",
    careersUrl: "https://block.xyz/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "block" },
    tier: "saas",
    enabled: false,
    domain: "block.xyz",
    category: "FINTECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Shopify",
    slug: "shopify",
    careersUrl: "https://www.shopify.com/careers",
    sourceType: "generic",
    tier: "saas",
    enabled: false,
    domain: "shopify.com",
    category: "SAAS",
    priority: "A",
    indiaHiring: "unknown",
  },
  {
    name: "Wise",
    slug: "wise",
    careersUrl: "https://wise.jobs/",
    sourceType: "generic",
    tier: "saas",
    enabled: false,
    domain: "wise.com",
    category: "FINTECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Revolut",
    slug: "revolut",
    careersUrl: "https://www.revolut.com/careers/",
    sourceType: "generic",
    tier: "saas",
    enabled: false,
    domain: "revolut.com",
    category: "FINTECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Adyen",
    slug: "adyen",
    careersUrl: "https://www.adyen.com/careers",
    sourceType: "generic",
    tier: "saas",
    enabled: false,
    domain: "adyen.com",
    category: "FINTECH",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Checkout.com",
    slug: "checkout-com",
    careersUrl: "https://www.checkout.com/careers",
    sourceType: "generic",
    tier: "saas",
    enabled: false,
    domain: "checkout.com",
    category: "FINTECH",
    priority: "C",
    indiaHiring: "unknown",
  },

  // AI / data / cloud
  {
    name: "Hugging Face",
    slug: "hugging-face",
    careersUrl: "https://huggingface.co/jobs",
    sourceType: "generic",
    tier: "ai",
    enabled: false,
    domain: "huggingface.co",
    category: "AI",
    priority: "A",
    indiaHiring: "unknown",
  },
  {
    name: "Scale AI",
    slug: "scale-ai",
    careersUrl: "https://scale.com/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "scaleai" },
    tier: "ai",
    enabled: false,
    domain: "scale.com",
    category: "AI",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Palantir",
    slug: "palantir",
    careersUrl: "https://www.palantir.com/careers/",
    sourceType: "generic",
    tier: "ai",
    enabled: false,
    domain: "palantir.com",
    category: "AI",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "DataStax",
    slug: "datastax",
    careersUrl: "https://www.datastax.com/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "datastax" },
    tier: "ai",
    enabled: false,
    domain: "datastax.com",
    category: "CLOUD",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Linear",
    slug: "linear",
    careersUrl: "https://linear.app/careers",
    sourceType: "ashby",
    sourceConfig: { boardToken: "linear" },
    tier: "saas",
    enabled: false,
    domain: "linear.app",
    category: "DEVTOOLS",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Supabase",
    slug: "supabase",
    careersUrl: "https://supabase.com/careers",
    sourceType: "ashby",
    sourceConfig: { boardToken: "supabase" },
    tier: "saas",
    enabled: false,
    domain: "supabase.com",
    category: "DEVTOOLS",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "PlanetScale",
    slug: "planetscale",
    careersUrl: "https://planetscale.com/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "planetscale" },
    tier: "saas",
    enabled: false,
    domain: "planetscale.com",
    category: "DEVTOOLS",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Neon",
    slug: "neon",
    careersUrl: "https://neon.tech/careers",
    sourceType: "ashby",
    sourceConfig: { boardToken: "neon" },
    tier: "saas",
    enabled: false,
    domain: "neon.tech",
    category: "DEVTOOLS",
    priority: "C",
    indiaHiring: "unknown",
  },

  // Indian product (official careers pages; ATS unknown until verified)
  {
    name: "Ola",
    slug: "ola",
    careersUrl: "https://www.olacabs.com/careers",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "olacabs.com",
    category: "INDIAN_PRODUCT",
    priority: "B",
    indiaHiring: "true",
  },
  {
    name: "Rapido",
    slug: "rapido",
    careersUrl: "https://rapido.bike/careers",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "rapido.bike",
    category: "INDIAN_PRODUCT",
    priority: "C",
    indiaHiring: "true",
  },
  {
    name: "Slice",
    slug: "slice",
    careersUrl: "https://sliceit.com/careers",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "sliceit.com",
    category: "INDIAN_PRODUCT",
    priority: "C",
    indiaHiring: "true",
  },
  {
    name: "Navi",
    slug: "navi",
    careersUrl: "https://navi.com/careers",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "navi.com",
    category: "INDIAN_PRODUCT",
    priority: "C",
    indiaHiring: "true",
  },
  {
    name: "OfBusiness",
    slug: "ofbusiness",
    careersUrl: "https://ofbusiness.com/careers",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "ofbusiness.com",
    category: "INDIAN_PRODUCT",
    priority: "C",
    indiaHiring: "true",
  },
  {
    name: "Udaan",
    slug: "udaan",
    careersUrl: "https://udaan.com/careers",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "udaan.com",
    category: "INDIAN_PRODUCT",
    priority: "C",
    indiaHiring: "true",
  },
  {
    name: "Apna",
    slug: "apna",
    careersUrl: "https://apna.co/careers",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "apna.co",
    category: "INDIAN_PRODUCT",
    priority: "C",
    indiaHiring: "true",
  },
  {
    name: "Unacademy",
    slug: "unacademy",
    careersUrl: "https://unacademy.com/careers",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "unacademy.com",
    category: "INDIAN_PRODUCT",
    priority: "C",
    indiaHiring: "true",
  },
  {
    name: "InCred",
    slug: "incred",
    careersUrl: "https://www.incred.com/careers",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "incred.com",
    category: "INDIAN_PRODUCT",
    priority: "C",
    indiaHiring: "true",
  },
  {
    name: "Policybazaar",
    slug: "policybazaar",
    careersUrl: "https://www.policybazaar.com/careers/",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "policybazaar.com",
    category: "INDIAN_PRODUCT",
    priority: "C",
    indiaHiring: "true",
  },
  {
    name: "Chargebee",
    slug: "chargebee",
    careersUrl: "https://www.chargebee.com/careers/",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "chargebee" },
    tier: "indian",
    enabled: false,
    domain: "chargebee.com",
    category: "SAAS",
    priority: "B",
    indiaHiring: "true",
  },
  {
    name: "CleverTap",
    slug: "clevertap",
    careersUrl: "https://clevertap.com/careers/",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "clevertap.com",
    category: "SAAS",
    priority: "B",
    indiaHiring: "true",
  },
  {
    name: "Whatfix",
    slug: "whatfix",
    careersUrl: "https://whatfix.com/careers/",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "whatfix.com",
    category: "SAAS",
    priority: "B",
    indiaHiring: "true",
  },
  {
    name: "WebEngage",
    slug: "webengage",
    careersUrl: "https://webengage.com/careers/",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "webengage.com",
    category: "SAAS",
    priority: "C",
    indiaHiring: "true",
  },
  {
    name: "InMobi",
    slug: "inmobi",
    careersUrl: "https://www.inmobi.com/careers",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "inmobi.com",
    category: "INDIAN_PRODUCT",
    priority: "B",
    indiaHiring: "true",
  },
  {
    name: "MoEngage",
    slug: "moengage",
    careersUrl: "https://www.moengage.com/careers/",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "moengage.com",
    category: "SAAS",
    priority: "B",
    indiaHiring: "true",
  },
  {
    name: "Hasura",
    slug: "hasura",
    careersUrl: "https://hasura.io/careers/",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "hasura" },
    tier: "indian",
    enabled: false,
    domain: "hasura.io",
    category: "DEVTOOLS",
    priority: "B",
    indiaHiring: "true",
  },
  {
    name: "Druva",
    slug: "druva",
    careersUrl: "https://www.druva.com/company/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "druva" },
    tier: "indian",
    enabled: false,
    domain: "druva.com",
    category: "CLOUD",
    priority: "B",
    indiaHiring: "true",
  },
  {
    name: "Icertis",
    slug: "icertis",
    careersUrl: "https://www.icertis.com/careers/",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "icertis.com",
    category: "SAAS",
    priority: "C",
    indiaHiring: "true",
  },
  {
    name: "LambdaTest",
    slug: "lambdatest",
    careersUrl: "https://www.lambdatest.com/careers",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "lambdatest.com",
    category: "DEVTOOLS",
    priority: "C",
    indiaHiring: "true",
  },

  // Additional product / engineering companies (official careers; ATS unknown until verified)
  {
    name: "Spotify",
    slug: "spotify",
    careersUrl: "https://www.lifeatspotify.com/",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "spotify.com",
    category: "CONSUMER_TECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Snap",
    slug: "snap",
    careersUrl: "https://careers.snap.com/",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "snap.com",
    category: "CONSUMER_TECH",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Zoom",
    slug: "zoom",
    careersUrl: "https://careers.zoom.us/",
    sourceType: "generic",
    tier: "saas",
    enabled: false,
    domain: "zoom.us",
    category: "SAAS",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Box",
    slug: "box",
    careersUrl: "https://www.box.com/careers",
    sourceType: "generic",
    tier: "saas",
    enabled: false,
    domain: "box.com",
    category: "SAAS",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Fastly",
    slug: "fastly",
    careersUrl: "https://www.fastly.com/about/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "fastly" },
    tier: "saas",
    enabled: false,
    domain: "fastly.com",
    category: "CLOUD",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Grammarly",
    slug: "grammarly",
    careersUrl: "https://www.grammarly.com/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "grammarly" },
    tier: "saas",
    enabled: false,
    domain: "grammarly.com",
    category: "AI",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Intuit",
    slug: "intuit",
    careersUrl: "https://www.intuit.com/careers/",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "intuit.com",
    category: "FINTECH",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Workday",
    slug: "workday",
    careersUrl: "https://www.workday.com/en-us/company/careers.html",
    sourceType: "generic",
    tier: "saas",
    enabled: false,
    domain: "workday.com",
    category: "SAAS",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Autodesk",
    slug: "autodesk",
    careersUrl: "https://www.autodesk.com/careers",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "autodesk.com",
    category: "OTHER_PRODUCT",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Tesla",
    slug: "tesla",
    careersUrl: "https://www.tesla.com/careers",
    sourceType: "generic",
    tier: "tier-1",
    enabled: false,
    domain: "tesla.com",
    category: "CONSUMER_TECH",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Unity",
    slug: "unity",
    careersUrl: "https://careers.unity.com/",
    sourceType: "generic",
    tier: "saas",
    enabled: false,
    domain: "unity.com",
    category: "DEVTOOLS",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Roblox",
    slug: "roblox",
    careersUrl: "https://careers.roblox.com/",
    sourceType: "generic",
    tier: "saas",
    enabled: false,
    domain: "roblox.com",
    category: "CONSUMER_TECH",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "JetBrains",
    slug: "jetbrains",
    careersUrl: "https://www.jetbrains.com/careers/",
    sourceType: "generic",
    tier: "saas",
    enabled: false,
    domain: "jetbrains.com",
    category: "DEVTOOLS",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Pinecone",
    slug: "pinecone",
    careersUrl: "https://www.pinecone.io/careers/",
    sourceType: "ashby",
    sourceConfig: { boardToken: "pinecone" },
    tier: "ai",
    enabled: false,
    domain: "pinecone.io",
    category: "AI",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Weights & Biases",
    slug: "weights-biases",
    careersUrl: "https://wandb.ai/site/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "weightsandbiases" },
    tier: "ai",
    enabled: false,
    domain: "wandb.ai",
    category: "AI",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "ElevenLabs",
    slug: "elevenlabs",
    careersUrl: "https://elevenlabs.io/careers",
    sourceType: "ashby",
    sourceConfig: { boardToken: "elevenlabs" },
    tier: "ai",
    enabled: false,
    domain: "elevenlabs.io",
    category: "AI",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Coursera",
    slug: "coursera",
    careersUrl: "https://about.coursera.org/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "coursera" },
    tier: "saas",
    enabled: false,
    domain: "coursera.org",
    category: "SAAS",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "Nutanix",
    slug: "nutanix",
    careersUrl: "https://www.nutanix.com/careers",
    sourceType: "generic",
    tier: "saas",
    enabled: false,
    domain: "nutanix.com",
    category: "CLOUD",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Sprinklr",
    slug: "sprinklr",
    careersUrl: "https://www.sprinklr.com/careers/",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "sprinklr.com",
    category: "SAAS",
    priority: "B",
    indiaHiring: "true",
  },
  {
    name: "ThoughtSpot",
    slug: "thoughtspot",
    careersUrl: "https://www.thoughtspot.com/careers",
    sourceType: "greenhouse",
    sourceConfig: { boardToken: "thoughtspot" },
    tier: "saas",
    enabled: false,
    domain: "thoughtspot.com",
    category: "AI",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Nykaa",
    slug: "nykaa",
    careersUrl: "https://www.nykaa.com/careers",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "nykaa.com",
    category: "INDIAN_PRODUCT",
    priority: "C",
    indiaHiring: "true",
  },
  {
    name: "Lenskart",
    slug: "lenskart",
    careersUrl: "https://www.lenskart.com/careers",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "lenskart.com",
    category: "INDIAN_PRODUCT",
    priority: "C",
    indiaHiring: "true",
  },
  {
    name: "BigBasket",
    slug: "bigbasket",
    careersUrl: "https://www.bigbasket.com/careers/",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "bigbasket.com",
    category: "INDIAN_PRODUCT",
    priority: "C",
    indiaHiring: "true",
  },
  {
    name: "Porter",
    slug: "porter",
    careersUrl: "https://porter.in/careers",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "porter.in",
    category: "INDIAN_PRODUCT",
    priority: "C",
    indiaHiring: "true",
  },
  {
    name: "Upstox",
    slug: "upstox",
    careersUrl: "https://upstox.com/careers/",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "upstox.com",
    category: "FINTECH",
    priority: "C",
    indiaHiring: "true",
  },
  {
    name: "Angel One",
    slug: "angel-one",
    careersUrl: "https://www.angelone.in/careers",
    sourceType: "generic",
    tier: "indian",
    enabled: false,
    domain: "angelone.in",
    category: "FINTECH",
    priority: "C",
    indiaHiring: "true",
  },
  {
    name: "Akamai",
    slug: "akamai",
    careersUrl: "https://www.akamai.com/careers",
    sourceType: "generic",
    tier: "saas",
    enabled: false,
    domain: "akamai.com",
    category: "CLOUD",
    priority: "C",
    indiaHiring: "unknown",
  },
  {
    name: "CrowdStrike",
    slug: "crowdstrike",
    careersUrl: "https://www.crowdstrike.com/careers/",
    sourceType: "generic",
    tier: "saas",
    enabled: false,
    domain: "crowdstrike.com",
    category: "SAAS",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Palo Alto Networks",
    slug: "palo-alto-networks",
    careersUrl: "https://jobs.paloaltonetworks.com/",
    sourceType: "generic",
    tier: "saas",
    enabled: false,
    domain: "paloaltonetworks.com",
    category: "SAAS",
    priority: "B",
    indiaHiring: "unknown",
  },
  {
    name: "Zscaler",
    slug: "zscaler",
    careersUrl: "https://www.zscaler.com/careers",
    sourceType: "generic",
    tier: "saas",
    enabled: false,
    domain: "zscaler.com",
    category: "SAAS",
    priority: "B",
    indiaHiring: "unknown",
  },
];
